export const CRUD_TODO_ENDPOINT = "/todos"
export const CRUD_TODO_LIST_ENDPOINT = `${CRUD_TODO_ENDPOINT}`
export const CRUD_TODO_ADD_ENDPOINT = `${CRUD_TODO_ENDPOINT}/add`
export const CRUD_TODO_UPDATE_ENDPOINT = `${CRUD_TODO_ENDPOINT}/update/{id}`
export const CRUD_TODO_DELETE_ENDPOINT = `${CRUD_TODO_ENDPOINT}/delete`
